configfile: "config/config.yaml"
report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/rafah.smk"
include: "rules/vhulk.smk"
include: "rules/vhmnet.smk"
include: "rules/htp.smk"
include: "rules/wish.smk"
include: "rules/crispropendb.smk"
include: "rules/phist.smk"

rule all:
    input:
        expand([
            "results/{sample}/phist/predictions.tsv"
            #"results/{sample}/tmp/reflist.txt",
            # "results/{sample}/{tool}/predictions.tsv",
            # "results/{sample}/all_predictions.tsv",
            # "results/{sample}/lca.tsv",
            # "report/{sample}_all.html",
            # "report/{sample}_lca.html",
            ],
            sample=SAMPLES, tool= TOOLS)
